version: 2

jobs:
  build:
    working_directory: ~/code
    docker:
      - image: circleci/android:api-25-alpha
    environment:
      ANDROID_HOME: /opt/android/sdk
      JVM_OPTS: -Xmx3200m
    steps:
      - checkout
      - restore_cache:
          key: jars-{{ checksum "build.gradle" }}-{{ checksum  "build.gradle" }}
#      - run:
#         name: Chmod permissions #if permission for Gradlew Dependencies fail, use this.
#         command: sudo chmod +x ./gradlew
      - run:
          name: Download Dependencies
          command: ./gradlew androidDependencies
      - save_cache:
          paths:
            - ~/.gradle
          key: jars-{{ checksum "build.gradle" }}-{{ checksum  "build.gradle" }}
      - run:
          name: Run Tests
          command: ./gradlew lint test
      - run:
          name: Run Checks
          command: ./gradlew check

      - store_artifacts:
          path: ~/code/core/build/reports
          destination: /build/reports

      - store_artifacts:
          path: ~/code/sampleapp/build/reports
          destination: /build/reports

      - run:
          name: Save test results
          command: |
            mkdir -p ~/junit/
            find . -type f -regex ".*/build/test-results/.*xml" -exec cp {} ~/junit/ \;
          when: always
      - store_test_results:
          path: ~/junit
      - store_artifacts:
          path: ~/junit 

      - run:
          name: Coverage upload
          command: |
            bash <(curl -s https://codecov.io/bash) \
              -F unittests \
              -f ~/junit/* \
              -t ${CODECOV_TOKEN} \

      # See https://circleci.com/docs/2.0/deployment-integrations/ for deploy examples